engine: surya
confidence_threshold: 0.7
language: "ar"
fallback_language: "en"
model_path: "models/surya_multilingual"
use_gpu: false
max_length: 512
batch_size: 4
temperature: 0.1
top_p: 0.9
do_sample: true
